language: node_js
node_js:
  - "7"
  - "6"
  - "4"
  - "0.12"
os:
  - linux
  - osx
after_success:
  - npm install coveralls
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
sudo: false
cache:
  - apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - export CXX="g++-4.8" CC="gcc-4.8"
