language: node_js
node_js:
  - "8"
  - "6"
  - "4"
  - "0.12"
os:
  - linux
  - osx
after_success:
  - npm install coveralls
  - nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls
sudo: false
cache:
  - apt
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
compiler: gcc
before_install:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then export CXX=g++-4.8; fi
install:
  - npm install $NPMOPT
script:
  - npm test
